[project]
name = "lapinou"
version = "0.1.0"
description = "An agentic game engine"
license = "AGPL-3.0-only"
readme = "README.md"
authors = [
    { name = "Jonathan Tremesaygues", email = "jonathan.tremesaygues@slaanesh.org" },
]
requires-python = ">=3.14"
dependencies = [
    "arcade>=2.4.3",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pydantic-ai-slim[google,openai]>=2.25.0",
    "python-dotenv>=1.2.2",
    "pymunk~=7.2.0",
]

[project.scripts]
lapinou = "lapinou.core.main:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
arcade = { git = "https://github.com/pythonarcade/arcade.git" }
