from os import environ

from pydantic_ai import Agent

from .models import Character


def create_agent(model: str | None = None) -> Agent:
    """
    Create and return an instance of the Agent class using the model specified in the environment variable.

    Returns:
        Agent: An instance of the Agent class initialized with the model from the environment variable.
    """
    return Agent(model or environ["LAPINOU_MODEL"])


def create_character(agent: Agent | None = None) -> Character:
    """
    Create and return a Character instance by running the agent with a prompt.

    Args:
        agent (Agent | None): An instance of the Agent class. If None, a new agent will be created.

    Returns:
        Character: An instance of the Character class generated by the agent.
    """
    if agent is None:
        agent = create_agent()

    return agent.run_sync("Generate a character", output_type=Character).output
